"""CLI commands for Tandemn"""

from http.client import responses
import click
from typing import Optional

from cli.validation_rules import (
    validate_engine_task,
    validate_features_for_task,
    validate_slo_mode,
    suggest_priority_from_deadline,
    suggest_engine_for_task,
    INFERENCE_ENGINES,
    IMAGE_ENGINES,
    ENGINE_TASK_COMPATIBILITY
    )
import datetime
from cli.api import TandemnAPI
from cli.auth import get_stored_credentials
import httpx
import asyncio
from cli.config_builder import build_job_config_from_cli_batched_vllm
from shared.config_transformation import convert_to_central_server_config
from pathlib import Path
from datetime import datetime

@click.command()
# select the Task First
@click.option("--task", "-t",
    type=click.Choice(["batched_inference", "online_serving", "embeddings", "image_generation"]),required=True,
    help="Please select one of -[ batched_inference | online_serving | embeddings | image_generation ]")
@click.option("--model", '-m',
    type=str, required=True,
    help="Please specify the huggingface model name")
@click.option("--input-file", "-if",
    type=str, required=False,
    help="This is an optional parameter and will be needed when we do batched inference. Please specify the local path of the file.")
@click.option("--output-file", "-of",
    type=str, required=False, default="output.txt",
    help="This is an optional parameter and will be needed when we do batched inference. Please specify the path of the output folder.")
@click.option("--engine", "-e", 
    type=click.Choice(INFERENCE_ENGINES), required=False,
    help="This is an optional field, if you want to specify the engine, select one from -[ vllm | sglang | diffusers | xDIT ]. Remember vllm sglang are text engines while diffusers and xDIT are image engines.")
@click.option("--description", "-d",
    type=str, required=False,
    help="Optional field, just needed in case you need to provide a description")
@click.option("--priority", "-p",
    type=click.Choice(["low", "normal", "high", "urgent"]), required=False,
    help="Select one of [ low | normal | high | urgent ]. This is optional, we will auto-generate based on the deadline. ")
@click.option("--sku", "-s",
    type=str,
    required=False,
    help="Please specify the GPU that you prefer (eg H100,A100,L40s)")
@click.option("--deadline", "-dl",
    type=int, 
    required=False,
    help="This is an optional field, only for batched inference so far. SLO Hours is in how many hours do you want the job to be done?")
@click.option("--slo-mode", "-sm",
    type=click.Choice(["offline", "online"]),
    required=False,
    help="Select one of [ offline | online ]. This is optional, and can be autogenerated based on the task and engine.")
@click.option("--speculative-decode", "-sd",
    is_flag=True, required=False,
    help="This is an optional field, only for text engines. If you want to use speculative decode, use this flag. This is only supported for vllm and sglang.")
@click.option("--pd-disaggregation", "-pd",
    is_flag=True, required=False,
    help="This is an optional field, only for text engines. If you want to use Prefill Decode Disaggregation, use this flag. This is only supported for vllm and sglang.")
@click.option("--quantization", "-q",
    type=click.Choice(["4", "8", "16"]), required=False,
    help="Select one of [ 4 | 8 | 16 ]. This is optional, we will check if the model has the same quantization or not?")
# vllm specific config
@click.option('--max-model-len',
    type=int, required=False,
    help='[vLLM] Max model context length')
@click.option('--max-num-seqs', type=int, required=False, help='[vLLM] Max concurrent sequences')
@click.option('--max-batched-tokens', type=int, required=False, help='[vLLM] Max batched tokens')
@click.option('--trust-remote-code', is_flag=True, required=False, default=True, help='[vLLM] Trust remote code')
@click.option('--tokenizer', help='[vLLM] Custom tokenizer path')
@click.option('--tokenizer-mode', 
    type=click.Choice(['auto', 'deepseek', 'mistral']), 
    required=False, default='auto', help='[vLLM] Tokenizer mode')
@click.option('--kv-cache-dtype', 
    type=click.Choice(['auto', 'bfloat16', 'fp8', 'fp8_ds_mla', 'fp8_e4m3', 'fp8_e5m2', 'fp8_inc']),
    required=False, help='[vLLM] KV cache data type')
@click.option('--config-format', 
    type=click.Choice(['auto', 'mistral']), 
    default='auto', help='[vLLM] Config format')
@click.option('--limit-mm', type=int, default=20, help='[vLLM] Limit multimodal per prompt')
@click.option('--speculative-method', 
    type=click.Choice(['ngram', 'suffix', 'eagle', 'eagle3', 'mlp_speculator', 'draft_model', 'mtp']),
    help='[Speculative] Decoding method')
@click.option('--num-spec-tokens', type=int, help='[Speculative] Number of speculative tokens')
@click.option('--draft-model', help='[Speculative] Draft model for speculative decoding')
@click.option('--prompt-lookup-max', type=int, help='[Speculative] Prompt lookup max (for ngram)')

@click.option('--dry-run', is_flag=True, help='Validate config without submitting')

def submit(
    # Required
    task: str,
    model: str,
    input_file: Optional[str], # only for batched inference
    output_file: Optional[str], # only for batched inference
    # Engine & Basic
    engine: Optional[str], # only for text engines
    description: Optional[str], # will mostly be generated by us
    priority: Optional[str], # we will auto-generate based on the deadline
    quantization: Optional[str], # only for text engines so far
    sku: Optional[str],
    slo_mode: Optional[str],
    deadline: Optional[int],
    speculative_decode: Optional[bool],
    pd_disaggregation: Optional[bool],
    max_model_len: Optional[int],
    max_num_seqs: Optional[int],
    max_batched_tokens: Optional[int],
    trust_remote_code: bool,
    tokenizer: Optional[str],
    tokenizer_mode: str,
    kv_cache_dtype: Optional[str],
    config_format: str,
    limit_mm: int,
    speculative_method: Optional[str],
    num_spec_tokens: Optional[int],
    draft_model: Optional[str],
    prompt_lookup_max: Optional[int],
    # Flags
    dry_run: bool,
    ):
    """
    Just to validate the config, check for errors, and submit to the central orchestrator server. 
    """
    # check if there are stored credentials
    # base_url, api_key = get_stored_credentials()
    # if not base_url or not api_key:
    #     click.echo("No stored credentials found, please run 'tandemn auth' to store your credentials")
    #     return

    base_url = "http://172.16.1.240:26336"
    click.echo(f"Found stored credentials, for the server URL: {base_url}")

    api = TandemnAPI(base_url=base_url)
    click.echo(f" Validating the Configuration...Please wait...")
    
    # auto-detect some important stuff if not specified
    if not engine:
        engine = suggest_engine_for_task(task)
        click.echo(f"Engine auto-detected as {engine}")
    
    if not slo_mode:
        slo_mode = "online" if task in ["online_serving", "image_generation"] else "offline"
        click.echo(f" SLO mode:{slo_mode} (auto-detected based on the task)")
    
    if not description:
        
        description = f"Job for {task} on {engine} model, date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    
    if not priority:
        priority = suggest_priority_from_deadline(deadline)
        click.echo(f" Priority auto-detected as {priority}")
    

    # Start the Validation Process
    errors=[]

    #1 - Task Engine Compatibility
    is_valid, error = validate_engine_task(engine, task)
    if not is_valid:
        errors.append(error)
        compatible = [e for e, tasks in ENGINE_TASK_COMPATIBILITY.items() if task in tasks]
        click.echo(f"💡For '{task}', use: {', '.join(compatible)}", err=True)
    
    is_valid, error = validate_features_for_task(task, speculative_decode, pd_disaggregation)
    if not is_valid:
        errors.append(error)
        click.echo("PD Disaggregation or Speculative Decoding are probably not supported for your task/engine combo", err=True)

    is_valid, error = validate_slo_mode(task, slo_mode)
    if not is_valid:
        errors.append(error)
        click.echo("You have selected an invalid SLO mode for your task", err=True)
    
    # if the vllm specific arguments are used and the engine is something else, throw in an error
    if engine != "vllm" and (max_model_len or max_num_seqs or max_batched_tokens or trust_remote_code or tokenizer or tokenizer_mode or kv_cache_dtype or config_format or limit_mm):
        errors.append("You have selected an invalid engine for your task, this param is just for vllm")

    # if any speculative arguments are used and speculative decode is not enabled, enable it
    if speculative_method or num_spec_tokens or draft_model or prompt_lookup_max and not speculative_decode:
        click.echo("   ⚠️  --speculative-method implies --speculative-decode, enabling it")
        speculative_decode = True
    
    if errors:
        click.echo("Validation Failed", err=True)
        for error in errors:
            click.echo(f"{error}", err=True)
        return
    
    click.echo("Validation Passed 😹", err=True)
    
    if dry_run:
        click.echo("📋 Dry run - would submit:")
        click.echo(f"   Task: {task}")
        click.echo(f"   Engine: {engine}")
        click.echo(f"   Model: {model}")
        click.echo(f"   File: {input_file}")
        click.echo(f"   Output File: {output_file}")
        click.echo(f"   Priority: {priority}")
        click.echo(f"   SLO: {slo_mode}" + (f" (deadline: {deadline}h)" if deadline else ""))
        if engine == "vllm":
            click.echo(f"   Max Model Len: {max_model_len or 'auto'}")
            click.echo(f"   Max Num Seqs: {max_num_seqs or 'auto'}")
            if speculative_decode:
                click.echo(f"   Speculative: {speculative_method or 'auto'}")
        # return
    
    # ==================== Build the Job Config =====================
    click.echo("📦 Building job configuration...")
    job_config = build_job_config_from_cli_batched_vllm(
        task=task,
        model=model,
        engine=engine,
        description=description,
        priority=priority,
        slo_mode=slo_mode,
        deadline=deadline,
        sku=sku,
        quantization=quantization,
        speculative_decode=speculative_decode,
        pd_disaggregation=pd_disaggregation,
        max_model_len=max_model_len,
        max_num_seqs=max_num_seqs,
        max_batched_tokens=max_batched_tokens,
        trust_remote_code=trust_remote_code,
    )
    click.echo("🔄 Applying defaults and validating with HuggingFace...")
    blob_storage_url = None

    if input_file and not dry_run:
        click.echo("🔄 Uploading input file to storage server...")
        remote_path = Path(input_file).name
        presigned_response = asyncio.run(api.presign_upload("s3://tandemn-user-data/"+remote_path, user="demo_user"))
       
        with open(input_file, "rb") as f:
            file_data = f.read()
        asyncio.run(api.upload_to_presigned_url(presigned_response, file_data))
        blob_storage_url = presigned_response['s3_uri']
        click.echo(f"Uploaded input file to storage server: {blob_storage_url}")

    # # now build the JobConfig and conver it to the Central Server Config
    # JobConfig = JobConfig(**job_config)
    click.echo("🔄 Building JobConfig...")
    central_server_config = convert_to_central_server_config(job_config, user_id="demo_user", selected_file=blob_storage_url, output_file=output_file)
    click.echo("🔄 Converted JobConfig to Central Server Config...")
    central_server_config_dict = central_server_config.model_dump()
    click.echo("🔄 Sending Central Server Config to Central Server...")
    async def submit():
        async with httpx.AsyncClient(timeout=2000.0) as client:
            response = await client.post(
                f"{base_url}/submit/batch",
                json=central_server_config_dict
            )
            response.raise_for_status()
            return response.json()
    if not dry_run:
        result = asyncio.run(submit())
        click.echo(f"✅ Job submitted!")
        click.echo(f"   Response: {result}")
    else:
        click.echo("🔄 Dry run - would submit:")
        click.echo(f"   Central Server Config: {central_server_config_dict}")
